<?php

namespace Database\Seeders;

use App\Models\Appointment;
use App\Models\Client;
use App\Models\ServiceRecord;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $admin = User::updateOrCreate([
            'email' => 'admin@appointpro.test',
        ], [
            'name' => 'System Admin',
            'role' => User::ROLE_ADMIN,
            'password' => Hash::make('password'),
        ]);

        $receptionist = User::updateOrCreate([
            'email' => 'reception@appointpro.test',
        ], [
            'name' => 'Front Desk',
            'role' => User::ROLE_RECEPTIONIST,
            'password' => Hash::make('password'),
        ]);

        $staff = User::updateOrCreate([
            'email' => 'staff@appointpro.test',
        ], [
            'name' => 'Service Staff',
            'role' => User::ROLE_STAFF,
            'password' => Hash::make('password'),
        ]);

        $client = Client::updateOrCreate([
            'phone' => '09171234567',
        ], [
            'first_name' => 'Alicia',
            'last_name' => 'Santos',
            'email' => 'alicia@example.com',
            'address' => 'Manila, Philippines',
            'notes' => 'Prefers afternoon schedules.',
        ]);

        $appointment = Appointment::updateOrCreate([
            'client_id' => $client->id,
            'appointment_date' => now()->addDay()->toDateString(),
            'appointment_time' => '10:30:00',
        ], [
            'staff_id' => $staff->id,
            'service_type' => 'Consultation',
            'status' => Appointment::STATUS_CONFIRMED,
            'notes' => 'Initial booking created by the receptionist.',
            'created_by' => $receptionist->id,
        ]);

        ServiceRecord::updateOrCreate([
            'appointment_id' => $appointment->id,
        ], [
            'client_id' => $client->id,
            'staff_id' => $staff->id,
            'description' => 'Follow-up summary placeholder record.',
            'service_date' => now()->toDateString(),
            'remarks' => 'Generated by the demo seeder.',
        ]);
    }
}
